<?php
/**
 * Landofcoder
 *
 * @category   Landofcoder
 * @package    Lof_LayeredNavigation
 * @copyright  Copyright (c) 2021 Landofcoder (https://www.landofcoder.com/)
 * @license    https://landofcoder.com/terms
 */
?>
<?php
/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\LayeredNavigation\ViewModel\Layer\Filter $viewModel */
$viewModel = $block->getData('product_layer_view_model');
$lofHelperData = $this->helper('Lof\LayeredNavigation\Helper\Data');
$enable_price_slider = $lofHelperData->getStoreConfig("layered_navigation/general/enable_price_slider");
?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php 
            $filter = $filterItem->getFilter();
            $attributeModel = $filter->getData('attribute_model');
            $inputName = $filter->getRequestVar();
            $getParamValue = $block->getRequest()->getParam($inputName);
            $requestArray = $getParamValue ? explode(',', $getParamValue) : [];
            $str = (string)$filterItem->getValue();
            if ($inputName == 'in-stock'){
                if (strpos($getParamValue, $str) !== false) {
                    $url = $filterItem->getRemoveUrl();
                } else {
                    $url = $filterItem->getUrl();
                }
            } else {
                $url = in_array($filterItem->getValue(), $requestArray) ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
            }
        ?>
        <li class="item">
            <?php if ($enable_price_slider && $attributeModel && $attributeModel->getFrontendInput() == 'price'): ?>
                <?php 
                $productCollection = $filter->getLayer()->getProductCollection();
                $collection = clone $productCollection;
                $minPrice = $collection->getMinPrice();
                $maxPrice = $collection->getMaxPrice();
                if (!$minPrice) {
                    $minPrice = $productCollection->getMinPrice();
                }
                if (!$maxPrice) {
                    $maxPrice = $productCollection->getMaxPrice();
                }
                list($from, $to) = $getParamValue ? explode('-', $getParamValue) : [$minPrice, $maxPrice];
                ?>
                <div id="lof_price_attribute">
                    <div id="lof_price_slider"></div>
                    <div id="lof_price_text"></div>
                </div>
                <script type="text/x-magento-init">
                    {
                        "#lof_price_attribute": {
                            "Lof_LayeredNavigation/js/price/slider": {
                                "selectedFrom": <?= $from ?>,
                                "selectedTo": <?= $to ?>,
                                "priceMin": <?= $minPrice ?>,
                                "priceMax": <?= $maxPrice ?>,
                                "priceFormat": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore()); ?>,
                                "ajaxUrl": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($filterItem->getUrl()) ?>
                            }
                        }
                    }
                </script>
                <?php break; ?>
            <?php else: ?>
				<?php if ($filterItem->getCount() >= 0): ?>
                    <a href="<?= $block->escapeUrl($url) ?>" class="lof-item">
                        <?php if ($attributeModel && $attributeModel->getFrontendInput() == 'multiselect' || $inputName == 'in-stock'): ?>
                            <?php if ($inputName == 'in-stock'): ?>
                                <input type="checkbox" <?= (strpos($getParamValue, $str) !== false)?'checked="checked"':''; ?> />
                            <?php else: ?>
                                <input type="checkbox" <?= in_array($filterItem->getValue(), $requestArray) ? 'checked="checked"' : ''  ?> />
                            <?php endif;?>
                        <?php endif; ?>
						<?= /* @noEscape */ $filterItem->getLabel() ?>
                        <?php if ($viewModel->shouldDisplayProductCountOnLayer()): ?>
                            <?php if ($filterItem->getCount() > 0):?>
                                <span class="count"><?= /* @noEscape */ (int) $filterItem->getCount()?><span class="filter-count-label">
                                <?php if ($filterItem->getCount() == 1):?>
                                    <?= $escaper->escapeHtml(__('item')) ?>
                                <?php else:?>
                                    <?= $escaper->escapeHtml(__('items')) ?>
                                <?php endif;?>
                                </span></span>
                            <?php endif; ?>
                        <?php endif; ?>
					</a>
                <?php else:?>
                    <?php if ($attributeModel && $attributeModel->getFrontendInput() == 'multiselect'): ?>
                        <input type="checkbox" disabled="disabled" />
                    <?php endif; ?>
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($viewModel->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @noEscape */ (int) $filterItem->getCount()?><span class="filter-count-label">
							<?php if ($filterItem->getCount() == 1):?><?= $escaper->escapeHtml(__('item')) ?><?php else:?><?= $escaper->escapeHtml(__('items')) ?><?php endif;?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>